"""adiciona remocao de membro com motivo, email de convocacao de reuniao e documento de posse do orgao

Revision ID: 00adf8a90706
Revises: 834a3a9e7775
Create Date: 2026-08-19 17:17:43.227060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00adf8a90706'
down_revision = '834a3a9e7775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('orgao_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documentos', 'orgaos_governanca', ['orgao_id'], ['id'])
    op.add_column('membros_orgao', sa.Column('motivo_remocao', sa.Text(), nullable=True))
    op.add_column(
        'reunioes',
        sa.Column('email_convocacao_enviado', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('reunioes', sa.Column('email_convocacao_enviado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reunioes', sa.Column('email_convocacao_destinatarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reunioes', sa.Column('email_convocacao_erro', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reunioes', 'email_convocacao_erro')
    op.drop_column('reunioes', 'email_convocacao_destinatarios')
    op.drop_column('reunioes', 'email_convocacao_enviado_em')
    op.drop_column('reunioes', 'email_convocacao_enviado')
    op.drop_column('membros_orgao', 'motivo_remocao')
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_column('documentos', 'orgao_id')
    # ### end Alembic commands ###
