"""modulo maturidade: editais, criterios, avaliacoes, recursos

Revision ID: 03a8cd5342ad
Revises: 45d01888a884
Create Date: 2026-07-30 23:34:25.736986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '03a8cd5342ad'
down_revision = '45d01888a884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editais',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ciclo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('limiar_cpl_em_desenvolvimento', sa.Float(), nullable=True),
    sa.Column('limiar_cpl_consolidada', sa.Float(), nullable=True),
    sa.Column('limiar_cpl_madura', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterios_maturidade',
    sa.Column('edital_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dimensao', sa.Enum('ORGANIZACAO', 'GOVERNANCA', 'PLANEJAMENTO', 'DIMENSAO', 'DIVERSIDADE', 'IMPACTO', name='dimensaomaturidade'), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('nota_corte', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes_maturidade',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('edital_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'CONCLUIDA', name='statusavaliacao'), nullable=False),
    sa.Column('avaliador_id', sa.UUID(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=False),
    sa.Column('pontuacao_calculada', sa.Float(), nullable=True),
    sa.Column('nivel_sugerido', postgresql.ENUM('AGLOMERADO_PRODUTIVO', 'CPL_EM_DESENVOLVIMENTO', 'CPL_CONSOLIDADA', 'CPL_MADURA', name='nivelmaturidade', create_type=False), nullable=True),
    sa.Column('nivel_decidido', postgresql.ENUM('AGLOMERADO_PRODUTIVO', 'CPL_EM_DESENVOLVIMENTO', 'CPL_CONSOLIDADA', 'CPL_MADURA', name='nivelmaturidade', create_type=False), nullable=True),
    sa.Column('parecer', sa.Text(), nullable=True),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('data_decisao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos_avaliacao',
    sa.Column('avaliacao_id', sa.UUID(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('solicitado_por_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'DEFERIDO', 'INDEFERIDO', name='statusrecurso'), nullable=False),
    sa.Column('parecer_decisao', sa.Text(), nullable=True),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('data_decisao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes_maturidade.id'], ),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id')
    )
    op.create_table('avaliacao_criterios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('avaliacao_id', sa.UUID(), nullable=False),
    sa.Column('criterio_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('evidencia_documento_id', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes_maturidade.id'], ),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios_maturidade.id'], ),
    sa.ForeignKeyConstraint(['evidencia_documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'criterio_id', name='uq_avaliacao_criterio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao_criterios')
    op.drop_table('recursos_avaliacao')
    op.drop_table('avaliacoes_maturidade')
    op.drop_table('criterios_maturidade')
    op.drop_table('editais')
    # ### end Alembic commands ###
