"""adiciona campos do gabarito CPLS-FORMS: endereco estruturado, capital humano, inovacao granular, internacionalizacao e consentimento LGPD

Revision ID: 0a0be2859e14
Revises: 776412f023c7
Create Date: 2026-08-20 16:43:42.971114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0be2859e14'
down_revision = '776412f023c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campanha_convites', sa.Column('consentimento_lgpd', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('campanha_convites', sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('situacao_vinculo_cpl', sa.String(length=255), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('materia_prima_principal', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('produto_principal', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('compra_de', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('vende_para', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('parcerias_instituicoes', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('funcionarios_clt', sa.Integer(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('terceirizados', sa.Integer(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('aprendizes', sa.Integer(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('colaboradores_pcd', sa.Integer(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('investimentos_recentes', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('pretende_investir', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('areas_investimento', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('tecnologias_utilizadas', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('desenvolve_novos_produtos', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('desenvolve_novos_processos', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_setor_pd', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_projetos_inovacao', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_patente', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_registro_software', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_marca_registrada', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('recebeu_recursos_publicos_inovacao', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('praticas_ambientais', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('importa', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_clientes_internacionais', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('participa_feiras_internacionais', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('interesse_exportar', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('necessidades_empresa', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('outras_demandas', sa.Text(), nullable=True))
    op.add_column('entidades', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('entidades', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('entidades', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('entidades', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('entidades', sa.Column('possui_filiais', sa.Boolean(), nullable=True))
    op.add_column('pessoas', sa.Column('whatsapp', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'whatsapp')
    op.drop_column('entidades', 'possui_filiais')
    op.drop_column('entidades', 'bairro')
    op.drop_column('entidades', 'complemento')
    op.drop_column('entidades', 'numero')
    op.drop_column('entidades', 'cep')
    op.drop_column('diagnosticos_cadastrais', 'outras_demandas')
    op.drop_column('diagnosticos_cadastrais', 'necessidades_empresa')
    op.drop_column('diagnosticos_cadastrais', 'interesse_exportar')
    op.drop_column('diagnosticos_cadastrais', 'participa_feiras_internacionais')
    op.drop_column('diagnosticos_cadastrais', 'possui_clientes_internacionais')
    op.drop_column('diagnosticos_cadastrais', 'importa')
    op.drop_column('diagnosticos_cadastrais', 'praticas_ambientais')
    op.drop_column('diagnosticos_cadastrais', 'recebeu_recursos_publicos_inovacao')
    op.drop_column('diagnosticos_cadastrais', 'possui_marca_registrada')
    op.drop_column('diagnosticos_cadastrais', 'possui_registro_software')
    op.drop_column('diagnosticos_cadastrais', 'possui_patente')
    op.drop_column('diagnosticos_cadastrais', 'possui_projetos_inovacao')
    op.drop_column('diagnosticos_cadastrais', 'possui_setor_pd')
    op.drop_column('diagnosticos_cadastrais', 'desenvolve_novos_processos')
    op.drop_column('diagnosticos_cadastrais', 'desenvolve_novos_produtos')
    op.drop_column('diagnosticos_cadastrais', 'tecnologias_utilizadas')
    op.drop_column('diagnosticos_cadastrais', 'areas_investimento')
    op.drop_column('diagnosticos_cadastrais', 'pretende_investir')
    op.drop_column('diagnosticos_cadastrais', 'investimentos_recentes')
    op.drop_column('diagnosticos_cadastrais', 'colaboradores_pcd')
    op.drop_column('diagnosticos_cadastrais', 'aprendizes')
    op.drop_column('diagnosticos_cadastrais', 'terceirizados')
    op.drop_column('diagnosticos_cadastrais', 'funcionarios_clt')
    op.drop_column('diagnosticos_cadastrais', 'parcerias_instituicoes')
    op.drop_column('diagnosticos_cadastrais', 'vende_para')
    op.drop_column('diagnosticos_cadastrais', 'compra_de')
    op.drop_column('diagnosticos_cadastrais', 'produto_principal')
    op.drop_column('diagnosticos_cadastrais', 'materia_prima_principal')
    op.drop_column('diagnosticos_cadastrais', 'situacao_vinculo_cpl')
    op.drop_column('campanha_convites', 'consentimento_em')
    op.drop_column('campanha_convites', 'consentimento_lgpd')
    # ### end Alembic commands ###
