"""modulo governanca: orgaos, membros, reunioes, presencas, deliberacoes, votos, tarefas, impedimentos

Revision ID: 0ba4d1a10f9d
Revises: 18541dca0a36
Create Date: 2026-07-29 16:25:24.535790

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0ba4d1a10f9d'
down_revision = '18541dca0a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgaos_governanca',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CONSELHO', 'CAMARA', 'COMISSAO_TEMATICA', 'GRUPO_TRABALHO', name='tipoorgao'), nullable=False),
    sa.Column('competencias', sa.Text(), nullable=True),
    sa.Column('quorum_minimo_percentual', sa.Float(), nullable=True),
    sa.Column('periodicidade', sa.String(length=100), nullable=True),
    sa.Column('estatuto_regimento_referencia', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membros_orgao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orgao_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('funcao', sa.String(length=150), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos_governanca.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunioes',
    sa.Column('orgao_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('pauta', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AGENDADA', 'REALIZADA', 'CANCELADA', name='statusreuniao'), nullable=False),
    sa.Column('convocada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ata', sa.Text(), nullable=True),
    sa.Column('quorum_atingido', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos_governanca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declaracoes_impedimento',
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('orgao_id', sa.UUID(), nullable=True),
    sa.Column('reuniao_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('data_declaracao', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos_governanca.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliberacoes',
    sa.Column('reuniao_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', 'ADIADA', 'SEM_QUORUM', name='resultadodeliberacao'), nullable=False),
    sa.Column('quorum_necessario_percentual', sa.Float(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('prazo_execucao', sa.Date(), nullable=True),
    sa.Column('evidencia_execucao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presencas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reuniao_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('justificativa_ausencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reuniao_id', 'pessoa_id', name='uq_presenca_reuniao_pessoa')
    )
    op.create_table('tarefas_governanca',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('deliberacao_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADA', 'CANCELADA', name='statustarefa'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['deliberacao_id'], ['deliberacoes.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deliberacao_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('voto', sa.Enum('A_FAVOR', 'CONTRA', 'ABSTENCAO', 'IMPEDIDO', name='tipovoto'), nullable=False),
    sa.Column('motivo_impedimento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deliberacao_id'], ['deliberacoes.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deliberacao_id', 'pessoa_id', name='uq_voto_deliberacao_pessoa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('tarefas_governanca')
    op.drop_table('presencas')
    op.drop_table('deliberacoes')
    op.drop_table('declaracoes_impedimento')
    op.drop_table('reunioes')
    op.drop_table('membros_orgao')
    op.drop_table('orgaos_governanca')
    # ### end Alembic commands ###
