"""remapeamento manual de colunas na importacao

Revision ID: 16a954e6a8d8
Revises: 03a8cd5342ad
Create Date: 2026-07-31 07:53:03.285981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16a954e6a8d8'
down_revision = '03a8cd5342ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajustes manuais: (1) `sa.Enum` dentro de `add_column` não cria o tipo
    # sozinho neste projeto (mesma classe de problema do gotcha de enum
    # reaproveitado, ver HANDOFF.md) — precisa de um `CREATE TYPE`
    # explícito antes. (2) já existem lotes de importação no banco (todos
    # processados no fluxo antigo de 1 passo), então a coluna NOT NULL
    # precisa de um server_default pra não quebrar o backfill — removido
    # logo em seguida, já que todo INSERT novo passa pelo default do
    # próprio modelo Python, não precisa continuar no schema.
    status_enum = postgresql.ENUM('PENDENTE_MAPEAMENTO', 'CONCLUIDO', name='statusloteimportacao')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'importacao_lotes',
        sa.Column(
            'status',
            postgresql.ENUM('PENDENTE_MAPEAMENTO', 'CONCLUIDO', name='statusloteimportacao', create_type=False),
            nullable=False,
            server_default='CONCLUIDO',
        ),
    )
    op.alter_column('importacao_lotes', 'status', server_default=None)
    op.add_column('importacao_lotes', sa.Column('arquivo_path', sa.String(length=500), nullable=True))
    op.add_column('importacao_lotes', sa.Column('mapeamento_colunas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importacao_lotes', 'mapeamento_colunas')
    op.drop_column('importacao_lotes', 'arquivo_path')
    op.drop_column('importacao_lotes', 'status')
    # ### end Alembic commands ###
