"""modelos base: cpl, entidade, pessoa, usuario

Revision ID: 18541dca0a36
Revises: 
Create Date: 2026-07-29 16:10:29.186942

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '18541dca0a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades',
    sa.Column('tipo', sa.Enum('EMPRESA', 'ORGAO_PUBLICO', 'UNIVERSIDADE', 'ICT', 'ASSOCIACAO', 'PRESTADOR', 'AMBIENTE_INOVACAO', name='tipoentidade'), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('cnae', sa.String(length=20), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('situacao_cadastral', sa.String(length=100), nullable=True),
    sa.Column('canais_digitais', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_cnpj'), 'entidades', ['cnpj'], unique=False)
    op.create_index(op.f('ix_entidades_cpf'), 'entidades', ['cpf'], unique=False)
    op.create_table('pessoas',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_cpf'), 'pessoas', ['cpf'], unique=False)
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=False)
    op.create_table('cpls',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=False),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('entidade_gestora_id', sa.UUID(), nullable=True),
    sa.Column('nivel_maturidade', sa.Enum('AGLOMERADO_PRODUTIVO', 'CPL_EM_DESENVOLVIMENTO', 'CPL_CONSOLIDADA', 'CPL_MADURA', name='nivelmaturidade'), nullable=True),
    sa.Column('data_reconhecimento', sa.Date(), nullable=True),
    sa.Column('data_validade_reconhecimento', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidade_gestora_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('usuarios',
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('entidade_cpl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('data_vinculo', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidade_id', 'cpl_id', name='uq_entidade_cpl')
    )
    op.create_table('entidade_elo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('elo', sa.Enum('INSUMOS', 'PRODUCAO', 'TRANSFORMACAO', 'COMERCIALIZACAO_DISTRIBUICAO', 'APOIO_INSTITUCIONAL', name='elo'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidade_id', 'cpl_id', 'elo', name='uq_entidade_cpl_elo')
    )
    op.create_table('pessoa_vinculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('papel', sa.Enum('ADMINISTRADOR_PLATAFORMA', 'ENTIDADE_GESTORA', 'DIRIGENTE_ENTIDADE_GESTORA', 'CONSELHO_COMITE', 'COMISSAO_TEMATICA', 'EMPRESA_MEMBRO', 'INSTITUICAO_ENSINO_ICT_SPAI', 'ANALISTA_AVALIADOR', 'GESTOR_PROJETO', 'AUDITORIA_CONTROLE', 'PUBLICO_EXTERNO', name='papel'), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_papel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.Enum('ADMINISTRADOR_PLATAFORMA', 'ENTIDADE_GESTORA', 'DIRIGENTE_ENTIDADE_GESTORA', 'CONSELHO_COMITE', 'COMISSAO_TEMATICA', 'EMPRESA_MEMBRO', 'INSTITUICAO_ENSINO_ICT_SPAI', 'ANALISTA_AVALIADOR', 'GESTOR_PROJETO', 'AUDITORIA_CONTROLE', 'PUBLICO_EXTERNO', name='papel'), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_papel')
    op.drop_table('pessoa_vinculo')
    op.drop_table('entidade_elo')
    op.drop_table('entidade_cpl')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('cpls')
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_cpf'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_entidades_cpf'), table_name='entidades')
    op.drop_index(op.f('ix_entidades_cnpj'), table_name='entidades')
    op.drop_table('entidades')
    # ### end Alembic commands ###
