"""adiciona ofertas de entidade e capacidade produtiva RF-010

Revision ID: 2f06d7b1b330
Revises: 48be8b55a24d
Create Date: 2026-08-06 06:59:14.399476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f06d7b1b330'
down_revision = '48be8b55a24d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas_entidade',
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUTO', 'SERVICO', 'TECNOLOGIA', name='tipooferta'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diagnosticos_cadastrais', sa.Column('capacidade_produtiva', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosticos_cadastrais', 'capacidade_produtiva')
    op.drop_table('ofertas_entidade')
    # ### end Alembic commands ###
