"""adiciona eventos e biblioteca de conhecimento RF-050 RF-051

Revision ID: 3163d6162f16
Revises: 4fc9db3f454d
Create Date: 2026-08-06 12:07:28.144914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3163d6162f16'
down_revision = '4fc9db3f454d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CAPACITACAO', 'MENTORIA', 'MISSAO_TECNICA', 'OUTRO', name='tipoevento'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AGENDADO', 'REALIZADO', 'CANCELADO', name='statusevento'), nullable=False),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos_biblioteca',
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('MODELO', 'ESTUDO', 'BOA_PRATICA', 'EDITAL', 'OPORTUNIDADE', 'CONTEUDO_TECNICO', name='tiporecursobiblioteca'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=True),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('url_externa', sa.String(length=500), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes_evento',
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('nota_avaliacao', sa.SmallInteger(), nullable=True),
    sa.Column('comentario_avaliacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'pessoa_id', name='uq_inscricao_evento_pessoa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes_evento')
    op.drop_table('recursos_biblioteca')
    op.drop_table('eventos')
    # ### end Alembic commands ###
