"""catalogo de indicadores: fonte, responsavel, serie historica

Revision ID: 45d01888a884
Revises: 5bff0df723be
Create Date: 2026-07-30 23:05:22.143734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d01888a884'
down_revision = '5bff0df723be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicador_valores_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicador_id', sa.UUID(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.UUID(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores_estrategicos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('indicadores_estrategicos', sa.Column('fonte', sa.String(length=255), nullable=True))
    op.add_column('indicadores_estrategicos', sa.Column('responsavel_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'indicadores_estrategicos', 'pessoas', ['responsavel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicadores_estrategicos', type_='foreignkey')
    op.drop_column('indicadores_estrategicos', 'responsavel_id')
    op.drop_column('indicadores_estrategicos', 'fonte')
    op.drop_table('indicador_valores_historico')
    # ### end Alembic commands ###
