"""adiciona recuperacao de senha e MFA RF-004

Revision ID: 48be8b55a24d
Revises: 69235b36be9e
Create Date: 2026-08-05 22:41:18.499228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48be8b55a24d'
down_revision = '69235b36be9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_recuperacao_senha',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_recuperacao_senha_token'), 'tokens_recuperacao_senha', ['token'], unique=True)
    op.add_column('usuarios', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('mfa_backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'mfa_backup_codes')
    op.drop_column('usuarios', 'mfa_secret')
    op.drop_index(op.f('ix_tokens_recuperacao_senha_token'), table_name='tokens_recuperacao_senha')
    op.drop_table('tokens_recuperacao_senha')
    # ### end Alembic commands ###
