"""adiciona registros de falha RNF-012

Revision ID: 4fc9db3f454d
Revises: ec51d69e4f77
Create Date: 2026-08-06 11:36:54.176070

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4fc9db3f454d'
down_revision = 'ec51d69e4f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_falha',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('rota', sa.String(length=500), nullable=False),
    sa.Column('tipo_excecao', sa.String(length=255), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('traceback_resumo', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_falha')
    # ### end Alembic commands ###
