"""adiciona plano de trabalho basico ao projeto (RF-033)

Revision ID: 55267d31bbca
Revises: 5dfb7c6bf49e
Create Date: 2026-08-04 09:27:13.622899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55267d31bbca'
down_revision = '5dfb7c6bf49e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('introducao', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('objeto', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('objetivos', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('justificativa', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('impactos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'impactos')
    op.drop_column('projetos', 'justificativa')
    op.drop_column('projetos', 'objetivos')
    op.drop_column('projetos', 'objeto')
    op.drop_column('projetos', 'introducao')
    # ### end Alembic commands ###
