"""modulo documentos: repositorio, versionamento, aprovacao, geracao de ata em PDF

Revision ID: 5891c62d1cb7
Revises: ac2ebdd62dd4
Create Date: 2026-07-30 18:30:16.434582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5891c62d1cb7'
down_revision = 'ac2ebdd62dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.Enum('ATA', 'PLANO_TRABALHO', 'DECLARACAO', 'COMPROVANTE', 'RELATORIO', 'OUTRO', name='categoriadocumento'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('confidencialidade', sa.Enum('PUBLICO', 'INTERNO', 'CONFIDENCIAL', name='confidencialidadedocumento'), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('documento_anterior_id', sa.UUID(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('aprovado_por_id', sa.UUID(), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('data_retencao_ate', sa.Date(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('reuniao_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['documento_anterior_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['reuniao_id'], ['reunioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
