"""adiciona trilha de auditoria

Revision ID: 5bff0df723be
Revises: 5891c62d1cb7
Create Date: 2026-07-30 18:56:13.662108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bff0df723be'
down_revision = '5891c62d1cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.Enum('CRIACAO', 'ATUALIZACAO', 'EXCLUSAO', 'LOGIN_SUCESSO', 'LOGIN_FALHA', 'DOWNLOAD', name='acaoauditoria'), nullable=False),
    sa.Column('entidade_tipo', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_auditoria')
    # ### end Alembic commands ###
