"""modulo planejamento estrategico: PEN, diagnostico, objetivos, metas, iniciativas, indicadores

Revision ID: 5dd913b79202
Revises: 0ba4d1a10f9d
Create Date: 2026-07-30 10:10:36.907481

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# 'elo' e 'statustarefa' já existem no banco (criados em migrações
# anteriores para EntidadeElo e TarefaGovernanca) — precisam de
# create_type=False aqui para não tentar recriar o tipo Postgres.
ELO_EXISTENTE = postgresql.ENUM(
    "INSUMOS", "PRODUCAO", "TRANSFORMACAO", "COMERCIALIZACAO_DISTRIBUICAO", "APOIO_INSTITUCIONAL",
    name="elo", create_type=False,
)
STATUS_TAREFA_EXISTENTE = postgresql.ENUM(
    "PENDENTE", "EM_ANDAMENTO", "CONCLUIDA", "ATRASADA", "CANCELADA",
    name="statustarefa", create_type=False,
)


# revision identifiers, used by Alembic.
revision = '5dd913b79202'
down_revision = '0ba4d1a10f9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planejamentos_estrategicos',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('ciclo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'EM_ELABORACAO', 'APROVADO', name='statusplanejamento'), nullable=False),
    sa.Column('caracterizacao', sa.Text(), nullable=True),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.Column('mercado', sa.Text(), nullable=True),
    sa.Column('inovacao', sa.Text(), nullable=True),
    sa.Column('impactos', sa.Text(), nullable=True),
    sa.Column('internacionalizacao', sa.Text(), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostico_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planejamento_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('FORCA', 'FRAQUEZA', 'OPORTUNIDADE', 'AMEACA', 'PROBLEMA_PRIORITARIO', 'DEMANDA', 'LACUNA_ELO', name='tipodiagnostico'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('elo_relacionado', ELO_EXISTENTE, nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planejamento_id'], ['planejamentos_estrategicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objetivos_estrategicos',
    sa.Column('planejamento_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo', sa.Enum('CURTO', 'MEDIO', 'LONGO', name='prazoobjetivo'), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('orcamento_estimado', sa.Float(), nullable=True),
    sa.Column('status', STATUS_TAREFA_EXISTENTE, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planejamento_id'], ['planejamentos_estrategicos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicadores_estrategicos',
    sa.Column('objetivo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('meta_valor', sa.String(length=255), nullable=True),
    sa.Column('valor_atual', sa.String(length=255), nullable=True),
    sa.Column('periodicidade', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos_estrategicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas_estrategicas',
    sa.Column('objetivo_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('status', STATUS_TAREFA_EXISTENTE, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos_estrategicos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_estrategicas',
    sa.Column('objetivo_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor_alvo', sa.String(length=255), nullable=False),
    sa.Column('metodo_afericao', sa.Text(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.Column('status', STATUS_TAREFA_EXISTENTE, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos_estrategicos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metas_estrategicas')
    op.drop_table('iniciativas_estrategicas')
    op.drop_table('indicadores_estrategicos')
    op.drop_table('objetivos_estrategicos')
    op.drop_table('diagnostico_itens')
    op.drop_table('planejamentos_estrategicos')
    # ### end Alembic commands ###
