"""adiciona modulo de projetos: demandas e portfolio (RF-031/032)

Revision ID: 5dfb7c6bf49e
Revises: d1b19a7c50fc
Create Date: 2026-08-03 18:01:51.850891

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5dfb7c6bf49e'
down_revision = 'd1b19a7c50fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandas_projeto',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('origem_tipo', sa.Enum('EMPRESA', 'COMISSAO', 'INSTITUICAO', 'EDITAL', name='origemdemanda'), nullable=False),
    sa.Column('origem_id', sa.UUID(), nullable=True),
    sa.Column('origem_detalhe', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('REGISTRADA', 'EM_ANALISE', 'CONVERTIDA_EM_PROJETO', 'REJEITADA', name='statusdemanda'), nullable=False),
    sa.Column('registrado_por_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('demanda_origem_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('eixo_sp_produz', sa.String(length=150), nullable=True),
    sa.Column('estagio', sa.Enum('DEMANDA', 'EM_ELABORACAO', 'SUBMETIDO', 'APROVADO', 'EM_EXECUCAO', 'CONCLUIDO', 'REJEITADO', 'CANCELADO', name='estagioprojeto'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='prioridadeprojeto'), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('objetivo_estrategico_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['demanda_origem_id'], ['demandas_projeto.id'], ),
    sa.ForeignKeyConstraint(['objetivo_estrategico_id'], ['objetivos_estrategicos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demanda_origem_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetos')
    op.drop_table('demandas_projeto')
    # ### end Alembic commands ###
