"""amplia diagnostico cadastral: qualificacao, sustentabilidade, contatos internacionais, certificacoes, digitalizacao e historico de empregos

Revision ID: 66fb5b2556d0
Revises: 16a954e6a8d8
Create Date: 2026-08-03 10:55:45.248273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fb5b2556d0'
down_revision = '16a954e6a8d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosticos_cadastrais_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('empregos_diretos', sa.Integer(), nullable=True),
    sa.Column('empregos_indiretos', sa.Integer(), nullable=True),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diagnosticos_cadastrais', sa.Column('oferece_qualificacao_colaboradores', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('descricao_qualificacao', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('adota_praticas_sustentabilidade', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('descricao_sustentabilidade', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_contatos_internacionais', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('descricao_contatos_internacionais', sa.Text(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('possui_certificacoes', sa.Boolean(), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('certificacoes', sa.String(length=255), nullable=True))
    op.add_column('diagnosticos_cadastrais', sa.Column('nivel_digitalizacao', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosticos_cadastrais', 'nivel_digitalizacao')
    op.drop_column('diagnosticos_cadastrais', 'certificacoes')
    op.drop_column('diagnosticos_cadastrais', 'possui_certificacoes')
    op.drop_column('diagnosticos_cadastrais', 'descricao_contatos_internacionais')
    op.drop_column('diagnosticos_cadastrais', 'possui_contatos_internacionais')
    op.drop_column('diagnosticos_cadastrais', 'descricao_sustentabilidade')
    op.drop_column('diagnosticos_cadastrais', 'adota_praticas_sustentabilidade')
    op.drop_column('diagnosticos_cadastrais', 'descricao_qualificacao')
    op.drop_column('diagnosticos_cadastrais', 'oferece_qualificacao_colaboradores')
    op.drop_table('diagnosticos_cadastrais_historico')
    # ### end Alembic commands ###
