"""adiciona execucao do projeto RF-039 RF-040

Revision ID: 69235b36be9e
Revises: 94d2ed47a842
Create Date: 2026-08-04 23:04:27.872783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '69235b36be9e'
down_revision = '94d2ed47a842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `statusrecurso` já existe (criado pra RecursoAvaliacao, RF-027) —
    # create_type=False evita "type already exists".
    op.create_table('alteracoes_plano_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_solicitacao', sa.Date(), nullable=False),
    sa.Column('solicitado_por_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDENTE', 'DEFERIDO', 'INDEFERIDO', name='statusrecurso', create_type=False), nullable=False),
    sa.Column('parecer_decisao', sa.Text(), nullable=True),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('data_decisao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('etapa_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('aprovado_por_id', sa.UUID(), nullable=True),
    sa.Column('data_aprovacao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas_projeto.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default explícito: coluna NOT NULL nova numa tabela que já
    # tem linhas — sem default, o ALTER TABLE falha contra elas (mesmo
    # gotcha de `aquisicoes_projeto.contrapartida`, migração bcae54b40941).
    op.add_column(
        'etapas_projeto',
        sa.Column('marco', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('riscos_projeto', sa.Column('evidencia_documento_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'riscos_projeto', 'documentos', ['evidencia_documento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riscos_projeto', type_='foreignkey')
    op.drop_column('riscos_projeto', 'evidencia_documento_id')
    op.drop_column('etapas_projeto', 'marco')
    op.drop_table('entregas_projeto')
    op.drop_table('alteracoes_plano_projeto')
    # ### end Alembic commands ###
