"""adiciona codigo do documento e aprovacoes/assinaturas necessarias

Revision ID: 776412f023c7
Revises: 00adf8a90706
Create Date: 2026-08-19 17:49:49.420922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776412f023c7'
down_revision = '00adf8a90706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprovacoes_documento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('APROVACAO', 'ASSINATURA', name='tipoaprovacaodocumento'), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('concluido_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Sequência criada antes da coluna: o `server_default` da coluna
    # `codigo` chama `nextval('documentos_codigo_seq')`, então a
    # sequência precisa existir primeiro — e como é um server_default
    # (não um valor fixo), o Postgres já usa ela pra popular o código de
    # cada linha existente durante o próprio ADD COLUMN, não só as novas.
    op.execute("CREATE SEQUENCE documentos_codigo_seq START 1")
    op.add_column('documentos', sa.Column('codigo', sa.String(length=30), server_default=sa.text("'DOC-' || lpad(nextval('documentos_codigo_seq')::text, 6, '0')"), nullable=False))
    op.create_unique_constraint(None, 'documentos', ['codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos', type_='unique')
    op.drop_column('documentos', 'codigo')
    op.execute("DROP SEQUENCE documentos_codigo_seq")
    op.drop_table('aprovacoes_documento')
    # ### end Alembic commands ###
