"""adiciona metas indicadores riscos e impactos socioambientais do plano de trabalho RF-034

Revision ID: 777ba9fa79ad
Revises: 336459855cb9
Create Date: 2026-08-04 14:04:13.124222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '777ba9fa79ad'
down_revision = '336459855cb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `statustarefa` já existe (criado pra TarefaGovernanca/ObjetivoEstrategico/
    # MetaEstrategica/EtapaProjeto) — create_type=False evita "type already exists".
    op.create_table('indicadores_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=100), nullable=True),
    sa.Column('meta_valor', sa.String(length=255), nullable=True),
    sa.Column('valor_atual', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('QUANTITATIVA', 'QUALITATIVA', name='tipometa'), nullable=False),
    sa.Column('valor_alvo', sa.String(length=255), nullable=True),
    sa.Column('valor_alcancado', sa.String(length=255), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADA', 'CANCELADA', name='statustarefa', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riscos_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('probabilidade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='probabilidaderisco'), nullable=False),
    sa.Column('impacto', sa.Enum('BAIXO', 'MEDIO', 'ALTO', name='impactorisco'), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'MITIGADO', 'MATERIALIZADO', 'ENCERRADO', name='statusrisco'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projetos', sa.Column('impactos_socioambientais', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'impactos_socioambientais')
    op.drop_table('riscos_projeto')
    op.drop_table('metas_projeto')
    op.drop_table('indicadores_projeto')
    # ### end Alembic commands ###
