"""adiciona email de comunicacoes da entidade e status de envio do convite

Revision ID: 834a3a9e7775
Revises: 92eefc2fd38f
Create Date: 2026-08-12 16:53:40.988343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '834a3a9e7775'
down_revision = '92eefc2fd38f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'campanha_convites',
        sa.Column('email_enviado', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('campanha_convites', sa.Column('email_enviado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campanha_convites', sa.Column('email_destinatarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campanha_convites', sa.Column('email_erro', sa.String(length=500), nullable=True))
    op.add_column('entidades', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entidades', 'email')
    op.drop_column('campanha_convites', 'email_erro')
    op.drop_column('campanha_convites', 'email_destinatarios')
    op.drop_column('campanha_convites', 'email_enviado_em')
    op.drop_column('campanha_convites', 'email_enviado')
    # ### end Alembic commands ###
