"""amplia ods_relacionados para text

Revision ID: 8ceb2431f363
Revises: 0a0be2859e14
Create Date: 2026-08-21 16:59:42.728315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ceb2431f363'
down_revision = '0a0be2859e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnosticos_cadastrais', 'ods_relacionados',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnosticos_cadastrais', 'ods_relacionados',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
