"""adiciona solicitacoes de adesao (F01)

Revision ID: 92eefc2fd38f
Revises: 970f9469baaa
Create Date: 2026-08-07 16:27:18.087456

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '92eefc2fd38f'
down_revision = '970f9469baaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_adesao',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('EMPRESA', 'ORGAO_PUBLICO', 'UNIVERSIDADE', 'ICT', 'ASSOCIACAO', 'PRESTADOR', 'AMBIENTE_INOVACAO', name='tipoentidade', create_type=False), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('elo_pretendido', postgresql.ENUM('INSUMOS', 'PRODUCAO', 'TRANSFORMACAO', 'COMERCIALIZACAO_DISTRIBUICAO', 'APOIO_INSTITUCIONAL', name='elo', create_type=False), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('contato_nome', sa.String(length=255), nullable=False),
    sa.Column('contato_email', sa.String(length=255), nullable=False),
    sa.Column('contato_telefone', sa.String(length=50), nullable=True),
    sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', name='statussolicitacaoadesao'), nullable=False),
    sa.Column('parecer', sa.Text(), nullable=True),
    sa.Column('analisado_por_id', sa.UUID(), nullable=True),
    sa.Column('data_analise', sa.Date(), nullable=True),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analisado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes_adesao')
    # ### end Alembic commands ###
