"""adiciona financeiro do projeto RF-036 RF-037 RF-038

Revision ID: 94d2ed47a842
Revises: bcae54b40941
Create Date: 2026-08-04 19:20:52.342838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d2ed47a842'
down_revision = 'bcae54b40941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacoes_aquisicao',
    sa.Column('aquisicao_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('selecionada', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquisicao_id'], ['aquisicoes_projeto.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desembolsos_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('aquisicao_id', sa.UUID(), nullable=True),
    sa.Column('origem_recurso_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('bem_adquirido', sa.String(length=255), nullable=True),
    sa.Column('documento_comprovante_id', sa.UUID(), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquisicao_id'], ['aquisicoes_projeto.id'], ),
    sa.ForeignKeyConstraint(['documento_comprovante_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['origem_recurso_id'], ['origens_recurso_projeto.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('aquisicoes_projeto', sa.Column('etapa_id', sa.UUID(), nullable=True))
    op.add_column('aquisicoes_projeto', sa.Column('origem_recurso_id', sa.UUID(), nullable=True))
    # server_default explícito: coluna NOT NULL nova numa tabela que já
    # pode ter linhas — sem default, o ALTER TABLE falha contra elas.
    op.add_column(
        'aquisicoes_projeto',
        sa.Column('contrapartida', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('aquisicoes_projeto', sa.Column('justificativa_excecao', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'aquisicoes_projeto', 'etapas_projeto', ['etapa_id'], ['id'])
    op.create_foreign_key(None, 'aquisicoes_projeto', 'origens_recurso_projeto', ['origem_recurso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aquisicoes_projeto', type_='foreignkey')
    op.drop_constraint(None, 'aquisicoes_projeto', type_='foreignkey')
    op.drop_column('aquisicoes_projeto', 'justificativa_excecao')
    op.drop_column('aquisicoes_projeto', 'contrapartida')
    op.drop_column('aquisicoes_projeto', 'origem_recurso_id')
    op.drop_column('aquisicoes_projeto', 'etapa_id')
    op.drop_table('desembolsos_projeto')
    op.drop_table('cotacoes_aquisicao')
    # ### end Alembic commands ###
