"""adiciona geolocalizacao de entidades RF-011

Revision ID: 970f9469baaa
Revises: bc65b64e9955
Create Date: 2026-08-07 13:19:52.945640

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '970f9469baaa'
down_revision = 'bc65b64e9955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidades', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('entidades', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entidades', 'longitude')
    op.drop_column('entidades', 'latitude')
    # ### end Alembic commands ###
