"""adiciona simulacao e habilitacao juridica RF-026 RF-027

Revision ID: a6b25ad2bdeb
Revises: 2f06d7b1b330
Create Date: 2026-08-06 07:44:40.858713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b25ad2bdeb'
down_revision = '2f06d7b1b330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_habilitacao_juridica',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('edital_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ENTREGUE', 'APROVADO', 'REJEITADO', name='statusitemhabilitacao'), nullable=False),
    sa.Column('parecer', sa.Text(), nullable=True),
    sa.Column('analisado_por_id', sa.UUID(), nullable=True),
    sa.Column('data_analise', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analisado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_habilitacao_juridica')
    # ### end Alembic commands ###
