"""cadastro dinamico: diagnostico, campanhas, convites, importacao de planilha

Revision ID: ac2ebdd62dd4
Revises: 5dd913b79202
Create Date: 2026-07-30 10:44:20.190751

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ac2ebdd62dd4'
down_revision = '5dd913b79202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosticos_cadastrais',
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('atividades_produtos', sa.Text(), nullable=True),
    sa.Column('diferenciais_competitivos', sa.Text(), nullable=True),
    sa.Column('faturamento_faixa', sa.String(length=100), nullable=True),
    sa.Column('empregos_diretos', sa.Integer(), nullable=True),
    sa.Column('empregos_indiretos', sa.Integer(), nullable=True),
    sa.Column('participacao_associativa', sa.Boolean(), nullable=True),
    sa.Column('entidades_associativas', sa.Text(), nullable=True),
    sa.Column('compartilha_recursos', sa.Boolean(), nullable=True),
    sa.Column('recursos_compartilhados', sa.Text(), nullable=True),
    sa.Column('realiza_inovacao', sa.Boolean(), nullable=True),
    sa.Column('descricao_inovacao', sa.Text(), nullable=True),
    sa.Column('realiza_pd', sa.Boolean(), nullable=True),
    sa.Column('ods_relacionados', sa.String(length=255), nullable=True),
    sa.Column('exporta', sa.Boolean(), nullable=True),
    sa.Column('mercados_exportacao', sa.Text(), nullable=True),
    sa.Column('interesse_comissoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidade_id')
    )
    op.create_table('campanhas_cadastrais',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao_lotes',
    sa.Column('cpl_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('total_linhas', sa.Integer(), nullable=False),
    sa.Column('total_criadas', sa.Integer(), nullable=False),
    sa.Column('total_atualizadas', sa.Integer(), nullable=False),
    sa.Column('total_erros', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campanha_convites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campanha_id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('respondido', sa.Boolean(), nullable=False),
    sa.Column('respondido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas_cadastrais.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanha_convites_token'), 'campanha_convites', ['token'], unique=True)
    op.create_table('importacao_linhas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('numero_linha', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CRIADA', 'ATUALIZADA', 'ERRO', name='statuslinhaimportacao'), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['importacao_lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importacao_linhas')
    op.drop_index(op.f('ix_campanha_convites_token'), table_name='campanha_convites')
    op.drop_table('campanha_convites')
    op.drop_table('importacao_lotes')
    op.drop_table('campanhas_cadastrais')
    op.drop_table('diagnosticos_cadastrais')
    # ### end Alembic commands ###
