"""adiciona matches de inovacao RF-052

Revision ID: bc65b64e9955
Revises: 3163d6162f16
Create Date: 2026-08-06 14:00:30.342629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc65b64e9955'
down_revision = '3163d6162f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches_inovacao',
    sa.Column('demanda_id', sa.UUID(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('oferta_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('SUGERIDO', 'EM_CONVERSA', 'FIRMADO', 'DESCARTADO', name='statusmatchinovacao'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('sugerido_por_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demanda_id'], ['demandas_projeto.id'], ),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas_entidade.id'], ),
    sa.ForeignKeyConstraint(['sugerido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demanda_id', 'entidade_id', name='uq_match_demanda_entidade')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches_inovacao')
    # ### end Alembic commands ###
