"""adiciona aquisicoes e cronograma fisico financeiro RF-035

Revision ID: bcae54b40941
Revises: c0bdeb29e88f
Create Date: 2026-08-04 15:23:55.405507

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bcae54b40941'
down_revision = 'c0bdeb29e88f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `statustarefa` já existe (criado pra TarefaGovernanca e reaproveitado
    # por vários outros modelos) — create_type=False evita "type already
    # exists".
    op.create_table('aquisicoes_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=150), nullable=True),
    sa.Column('quantidade', sa.String(length=100), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADA', 'CANCELADA', name='statustarefa', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('etapas_projeto', sa.Column('valor_previsto', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('etapas_projeto', sa.Column('valor_executado', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etapas_projeto', 'valor_executado')
    op.drop_column('etapas_projeto', 'valor_previsto')
    op.drop_table('aquisicoes_projeto')
    # ### end Alembic commands ###
