"""adiciona edital de fomento e recursos de submissao RF-029 RF-030

Revision ID: c0bdeb29e88f
Revises: d798be587a1c
Create Date: 2026-08-04 15:00:46.391674

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0bdeb29e88f'
down_revision = 'd798be587a1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `statusrecurso` já existe (criado pra RecursoAvaliacao, RF-027) —
    # create_type=False evita "type already exists".
    op.create_table('editais_fomento',
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('documentos_exigidos', sa.Text(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos_submissao_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('RECURSO', 'CONTRARRAZAO', 'DILIGENCIA', name='tiporecursosubmissao'), nullable=False),
    sa.Column('protocolo', sa.String(length=100), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('solicitado_por_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDENTE', 'DEFERIDO', 'INDEFERIDO', name='statusrecurso', create_type=False), nullable=False),
    sa.Column('parecer_decisao', sa.Text(), nullable=True),
    sa.Column('decidido_por_id', sa.UUID(), nullable=True),
    sa.Column('data_decisao', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projetos', sa.Column('edital_fomento_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projetos', 'editais_fomento', ['edital_fomento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.drop_column('projetos', 'edital_fomento_id')
    op.drop_table('recursos_submissao_projeto')
    op.drop_table('editais_fomento')
    # ### end Alembic commands ###
