"""adiciona notificacoes automaticas de prazos e pendencias (RF-049)

Revision ID: d1b19a7c50fc
Revises: 66fb5b2556d0
Create Date: 2026-08-03 16:27:48.517362

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1b19a7c50fc'
down_revision = '66fb5b2556d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cpl_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('REUNIAO_PROXIMA', 'TAREFA_PRAZO', 'DOCUMENTO_VALIDADE', 'META_PRAZO', 'RECADASTRAMENTO_CPL', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('entidade_tipo', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpl_id'], ['cpls.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
