"""adiciona equipe e origem de recursos do projeto RF-035

Revision ID: d798be587a1c
Revises: 777ba9fa79ad
Create Date: 2026-08-04 14:36:09.725496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd798be587a1c'
down_revision = '777ba9fa79ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=False),
    sa.Column('funcao', sa.String(length=150), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('origens_recurso_projeto',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('fonte', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contrapartida', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projetos', sa.Column('continuidade', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('escalabilidade', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'escalabilidade')
    op.drop_column('projetos', 'continuidade')
    op.drop_table('origens_recurso_projeto')
    op.drop_table('equipe_projeto')
    # ### end Alembic commands ###
