"""adiciona requisitos de habilitacao do edital RF-003

Revision ID: ec51d69e4f77
Revises: a6b25ad2bdeb
Create Date: 2026-08-06 10:57:51.547867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec51d69e4f77'
down_revision = 'a6b25ad2bdeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisitos_habilitacao_edital',
    sa.Column('edital_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisitos_habilitacao_edital')
    # ### end Alembic commands ###
